# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

permissions:
  content: write
  pages: write
  pull-requests: write
  id-token: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bazel
        uses: bazelbuild/setup-bazel@v3

      - name: Build documentation
        run: |
          # Creating a non-root user named 'nonrootuser'
          sudo useradd -m nonrootuser || true
          # Running Bazel build command as non-root user
          sudo -u nonrootuser -H bash -c 'bazel build //docs:github_pages'
