name: Static Analysis CI

on:
  workflow_dispatch:
    inputs:
      bazel-target:
        description: "Custom Bazel target to run (e.g.: 'test //src/...')"
        required: false
        default: "test //..."
        type: string

jobs:
  static-analysis:
    uses: eclipse-score/cicd-workflows/.github/workflows/static-analysis.yml@main
    with:
      bazel-target: "run //:static-analysis" # optional, this is the default
